
#YOUR BOT TOKEN FOR MOR INFO VISIT https://core.telegram.org/bots/api#authorizing-your-bot
TOKEN =''

#TWO CHANNEL ID'S ONE FOR VERIFICATION ONE FOR SAVING VIDEOS
CHANNEL=-100
VERIFICATIONCHANNEL=-100

#YOUR TELEGRAM USER ID
ADMIN=

#DATABASE
DB=''
DBPASS = ''
USERDB = ''
HOST=''


#DO NOT CHANGE
ADMINVIDEO,  ADMINTAGS = range(2)
USERVIDEO, USERTAGS = range(2)
